### ISSUE TITLE
Remove old requirements.txt file

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/cultivar#86]
need to remove the [`requirements.txt` file](https://github.com/DistrictDataLabs/cultivar/blob/master/requirements.txt) from the repository and in the contribution guide direct developers to ```pip install -r requirements/local.txt``` instead of ```pip install -r requirements.txt```

**Comment by rebeccabilbro** [comment]
also need to remove the dependency that's causing the `map has no len()` error

**Comment by rebeccabilbro** [comment]
from sasan: 

```bash
Traceback (most recent call last):
 File "manage.py", line 39, in <module>
   execute_from_command_line(sys.argv)
 File "/Users/sasanbahadaran/.virtualenvs/celery/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
   utility.execute()
 File "/Users/sasanbahadaran/.virtualenvs/celery/lib/python3.5/site-packages/django/core/management/__init__.py", line 327, in execute
   django.setup()
 File "/Users/sasanbahadaran/.virtualenvs/celery/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
   apps.populate(settings.INSTALLED_APPS)
 File "/Users/sasanbahadaran/.virtualenvs/celery/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
   app_config.import_models(all_models)
 File "/Users/sasanbahadaran/.virtualenvs/celery/lib/python3.5/site-packages/django/apps/config.py", line 202, in import_models
   self.models_module = import_module(models_module_name)
 File "/Users/sasanbahadaran/.virtualenvs/celery/lib/python3.5/importlib/__init__.py", line 126, in import_module
   return _bootstrap._gcd_import(name[level:], package, level)
 File "<frozen importlib._bootstrap>", line 986, in _gcd_import
 File "<frozen importlib._bootstrap>", line 969, in _find_and_load
 File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
 File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
 File "<frozen importlib._bootstrap_external>", line 662, in exec_module
 File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
 File "/Users/sasanbahadaran/.virtualenvs/celery/lib/python3.5/site-packages/social/apps/django_app/default/models.py", line 9, in <module>
   from social.storage.django_orm import DjangoUserMixin, \
 File "/Users/sasanbahadaran/.virtualenvs/celery/lib/python3.5/site-packages/social/storage/django_orm.py", line 5, in <module>
   from social.storage.base import UserMixin, AssociationMixin, NonceMixin, \
 File "/Users/sasanbahadaran/.virtualenvs/celery/lib/python3.5/site-packages/social/storage/base.py", line 12, in <module>
   from openid.association import Association as OpenIdAssociation
 File "/Users/sasanbahadaran/.virtualenvs/celery/lib/python3.5/site-packages/openid/__init__.py", line 52, in <module>
   if len(version_info) != 3:
TypeError: object of type 'map' has no len()
```

**Comment by rebeccabilbro** [comment]
looks like the dependency problem is with [`python3-openid`](https://pypi.python.org/pypi/python3-openid)

**Comment by bbengfort** [comment]
Attempted fix, modified requirements/base.txt to only have socialauth as a dependency and removed the openid dependencies.
